### PR TITLE
add metadata remove subverb

### LINKED ISSUE #2: Provide a remove verb
Users can add metadata repositories via commandline but currently cannot remove them and have to go remove / edit the metadata_repositories.yaml by hand

### PR DESCRIPTION
**Pull request by dirk-thomas**
Fixes #2.

### CODE REVIEW

**Review by mikaelarguedas — CHANGES_REQUESTED** [review]
`RemoveMetadataSubverb` doesn't exist as the feature has been added to the `UpdateMetadataSubverb` class

**Comment by dirk-thomas** [comment]
The new file was just missing from the commit: added in e47b9043c32d666fb0e34c39e7ba304f5a35ce5d.

Please re-review.

**Comment by mikaelarguedas** [comment]
Maybe I'm doing something wrong. How did you test this ?

```
ERROR:colcon:colcon metadata: unsupported operand type(s) for -=: 'set' and 'list'
Traceback (most recent call last):
  File "/home/mikael/work/ros2/colcon/install/colcon-core/lib/python3.5/site-packages/colcon_core/command.py", line 358, in verb_main
    rc = context.args.main(context=context)
  File "/home/mikael/work/ros2/colcon/install/colcon-metadata/lib/python3.5/site-packages/colcon_metadata/subverb/update.py", line 142, in main
    repository_name=name)
TypeError: unsupported operand type(s) for -=: 'set' and 'list'
```

**Comment by dirk-thomas** [comment]
```
$ colcon metadata list
$ colcon metadata add default https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml
$ colcon metadata list
default: https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml
$ colcon metadata remove default
$ colcon metadata list
```

**Comment by dirk-thomas** [comment]
Fixed in 6da5b7cd393b2a08e9c59cab502a7c093a3a35c9.

```
$ colcon metadata list
$ colcon metadata add default https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml
$ colcon metadata list
default: https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml
$ colcon metadata update
fetching default: https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml ...
  fetching https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/Gazebo.meta ...
  + ~/.colcon/metadata/default/Gazebo.meta
$ colcon metadata remove default
$ colcon metadata list
$ colcon metadata update
  - /home/dthomas/.colcon/metadata/default/Gazebo.meta -> *.obsolete
```

**Review by mikaelarguedas — APPROVED** [review]
It works for me now.

Can you please just push new commits in the future rather than force pushing ? this helps for reviewing.
We can then squash them at merge time.

**Pull request merged**
